// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/v1/gateway.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// SubmitTransactionRequest is the payload sent by the client to submit a
// payment transaction for processing.
type SubmitTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Idempotency key for deduplication.
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Raw PAN – hashed at the gateway boundary; never stored.
	Pan string `protobuf:"bytes,2,opt,name=pan,proto3" json:"pan,omitempty"`
	// Card expiry.
	ExpiryMonth uint32 `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear  uint32 `protobuf:"varint,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	// Transaction amount in minor currency units (e.g. cents).
	AmountMinor int64 `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	// ISO 4217 currency code, e.g. "USD".
	CurrencyCode string `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// Transaction type: SALES, VOID, REFUND, REVERSAL.
	TransactionType string `protobuf:"bytes,7,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	// Channel: POS, PG.
	Channel string `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	// ISO 18245 Merchant Category Code (4-digit string).
	MerchantCategoryCode string `protobuf:"bytes,9,opt,name=merchant_category_code,json=merchantCategoryCode,proto3" json:"merchant_category_code,omitempty"`
	// Terminal and merchant identifiers.
	TerminalId string `protobuf:"bytes,10,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	MerchantId string `protobuf:"bytes,11,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// Retrieval Reference Number (optional).
	RetrievalReferenceNumber string `protobuf:"bytes,12,opt,name=retrieval_reference_number,json=retrievalReferenceNumber,proto3" json:"retrieval_reference_number,omitempty"`
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
}

func (x *SubmitTransactionRequest) String() string {
	return x.IdempotencyKey
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

// SubmitTransactionResponse is returned after a transaction is accepted.
type SubmitTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId     string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Duplicate bool   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
}

func (x *SubmitTransactionResponse) String() string {
	return x.TxnId
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

// GetTransactionStatusRequest is used to query the status of a transaction.
type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
}

func (x *GetTransactionStatusRequest) String() string {
	return x.TxnId
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

// GetTransactionStatusResponse carries the current status of a transaction.
type GetTransactionStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId  string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetTransactionStatusResponse) Reset() {
	*x = GetTransactionStatusResponse{}
}

func (x *GetTransactionStatusResponse) String() string {
	return x.TxnId
}

func (*GetTransactionStatusResponse) ProtoMessage() {}

func (x *GetTransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
