// =============================================================================
// SentinelSwitch — API Gateway Inbound Contract
// Service : GatewayService
// Ticket  : CREDO-ALERT-001
//
// This file defines the synchronous gRPC surface that the API Gateway
// exposes to merchant-facing clients (POS terminals, payment-page SDKs).
//
// Request flow:
//   Client → API Gateway (SubmitTransaction)
//            ├─ publishes TransactionEvent to Kafka topic: transactions
//            └─ returns TransactionAck (txn_id + initial_status) immediately
//
// The fraud decision is asynchronous.  Clients that need the final
// fraud result must either:
//   a) poll  GetTransactionStatus(txn_id)  — suitable for POS/PG
//   b) subscribe to a webhook (configured per merchant, out of scope here)
//
// Authorization:
//   Every call must carry a valid Bearer JWT in the gRPC metadata key
//   "authorization".  The JWT is validated by the API Gateway before the
//   handler runs.  Merchant claims are embedded in the token; the gateway
//   derives merchant_id from the JWT rather than trusting the request body.
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/gateway.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GatewayService_SubmitTransaction_FullMethodName    = "/sentinel.gateway.v1.GatewayService/SubmitTransaction"
	GatewayService_GetTransactionStatus_FullMethodName = "/sentinel.gateway.v1.GatewayService/GetTransactionStatus"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	// Submit a new transaction for fraud analysis.
	// Returns immediately with a txn_id and PENDING status.
	// SLA: P99 < 50 ms (gateway only — excludes async fraud processing).
	SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionAck, error)
	// Poll the fraud decision for a previously submitted transaction.
	// Returns NOT_FOUND if the txn_id is unknown or has expired from cache.
	// SLA: P99 < 30 ms (Redis cache read).
	GetTransactionStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) SubmitTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionAck)
	err := c.cc.Invoke(ctx, GatewayService_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetTransactionStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*TransactionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionStatusResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations should embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	// Submit a new transaction for fraud analysis.
	// Returns immediately with a txn_id and PENDING status.
	// SLA: P99 < 50 ms (gateway only — excludes async fraud processing).
	SubmitTransaction(context.Context, *TransactionRequest) (*TransactionAck, error)
	// Poll the fraud decision for a previously submitted transaction.
	// Returns NOT_FOUND if the txn_id is unknown or has expired from cache.
	// SLA: P99 < 30 ms (Redis cache read).
	GetTransactionStatus(context.Context, *StatusRequest) (*TransactionStatusResponse, error)
}

// UnimplementedGatewayServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) SubmitTransaction(context.Context, *TransactionRequest) (*TransactionAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedGatewayServiceServer) GetTransactionStatus(context.Context, *StatusRequest) (*TransactionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SubmitTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetTransactionStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _GatewayService_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _GatewayService_GetTransactionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
