// =============================================================================
// SentinelSwitch — API Gateway Inbound Contract
// Service : GatewayService
// Ticket  : CREDO-ALERT-001
//
// This file defines the synchronous gRPC surface that the API Gateway
// exposes to merchant-facing clients (POS terminals, payment-page SDKs).
//
// Request flow:
//   Client → API Gateway (SubmitTransaction)
//            ├─ publishes TransactionEvent to Kafka topic: transactions
//            └─ returns TransactionAck (txn_id + initial_status) immediately
//
// The fraud decision is asynchronous.  Clients that need the final
// fraud result must either:
//   a) poll  GetTransactionStatus(txn_id)  — suitable for POS/PG
//   b) subscribe to a webhook (configured per merchant, out of scope here)
//
// Authorization:
//   Every call must carry a valid Bearer JWT in the gRPC metadata key
//   "authorization".  The JWT is validated by the API Gateway before the
//   handler runs.  Merchant claims are embedded in the token; the gateway
//   derives merchant_id from the JWT rather than trusting the request body.
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/gateway.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_PENDING                        TransactionStatus = 1 // Submitted; awaiting fraud decision
	TransactionStatus_APPROVED                       TransactionStatus = 2 // Fraud engine approved
	TransactionStatus_DECLINED                       TransactionStatus = 3 // Fraud engine declined
	TransactionStatus_REVIEW                         TransactionStatus = 4 // Flagged for manual review
	TransactionStatus_ERROR                          TransactionStatus = 5 // Processing error; retry safe
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "APPROVED",
		3: "DECLINED",
		4: "REVIEW",
		5: "ERROR",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"PENDING":                        1,
		"APPROVED":                       2,
		"DECLINED":                       3,
		"REVIEW":                         4,
		"ERROR":                          5,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_gateway_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_SALES                        TransactionType = 1
	TransactionType_VOID                         TransactionType = 2
	TransactionType_REFUND                       TransactionType = 3
	TransactionType_REVERSAL                     TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "SALES",
		2: "VOID",
		3: "REFUND",
		4: "REVERSAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"SALES":                        1,
		"VOID":                         2,
		"REFUND":                       3,
		"REVERSAL":                     4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_proto_enumTypes[1].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_gateway_proto_enumTypes[1]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_POS                 Channel = 1 // Point-of-sale terminal
	Channel_PG                  Channel = 2 // Payment gateway (e-commerce)
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "POS",
		2: "PG",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"POS":                 1,
		"PG":                  2,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gateway_proto_enumTypes[2].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_proto_gateway_proto_enumTypes[2]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

type TransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ------------------------------------------------------------------
	// Card data
	// The gateway receives the raw PAN and hashes it (SHA-256 + HMAC-SHA256
	// with a per-environment secret) before forwarding downstream.
	// Raw PAN is NEVER written to Kafka, logs, or any persistent store.
	// ------------------------------------------------------------------
	PanLast4   string `protobuf:"bytes,1,opt,name=pan_last4,json=panLast4,proto3" json:"pan_last4,omitempty"`       // Last 4 digits only — for receipt / display
	CardExpiry string `protobuf:"bytes,2,opt,name=card_expiry,json=cardExpiry,proto3" json:"card_expiry,omitempty"` // MM/YY — used for basic validity check only
	CardHash   string `protobuf:"bytes,3,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`       // SHA-256(HMAC-SHA256(pan, secret)) — set by
	// ------------------------------------------------------------------
	// Amount
	// amount_minor : transaction value in the currency's minor units
	// e.g. OMR 5.250 → amount_minor = 5250, currency = "OMR"
	// ------------------------------------------------------------------
	AmountMinor int64  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency    string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217 — e.g. "OMR", "USD", "EUR"
	// ------------------------------------------------------------------
	// Merchant context
	// merchant_id is derived from the JWT; clients cannot override it.
	// The gateway populates it from the JWT claim before Kafka publish.
	// ------------------------------------------------------------------
	MerchantId string `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"` // Read-only: populated from JWT by gateway
	Mcc        string `protobuf:"bytes,7,opt,name=mcc,proto3" json:"mcc,omitempty"`                                 // ISO 18245 — merchant category code
	// ------------------------------------------------------------------
	// Transaction classification
	// ------------------------------------------------------------------
	TransactionType TransactionType `protobuf:"varint,8,opt,name=transaction_type,json=transactionType,proto3,enum=sentinel.gateway.v1.TransactionType" json:"transaction_type,omitempty"`
	Channel         Channel         `protobuf:"varint,9,opt,name=channel,proto3,enum=sentinel.gateway.v1.Channel" json:"channel,omitempty"`
	// ------------------------------------------------------------------
	// Terminal (sent by the client device — gateway cannot derive this)
	// ------------------------------------------------------------------
	TerminalId string `protobuf:"bytes,11,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"` // POS terminal ID or PG session ID
	// ------------------------------------------------------------------
	// Idempotency
	// Clients MUST supply a unique idempotency_key per logical transaction.
	// The gateway rejects duplicate keys within a 24-hour window (HTTP 409
	// / gRPC ALREADY_EXISTS) and returns the original TransactionAck.
	// Recommended: UUID v4 generated by the client.
	// ------------------------------------------------------------------
	IdempotencyKey string `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetPanLast4() string {
	if x != nil {
		return x.PanLast4
	}
	return ""
}

func (x *TransactionRequest) GetCardExpiry() string {
	if x != nil {
		return x.CardExpiry
	}
	return ""
}

func (x *TransactionRequest) GetCardHash() string {
	if x != nil {
		return x.CardHash
	}
	return ""
}

func (x *TransactionRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *TransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TransactionRequest) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *TransactionRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *TransactionRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TransactionAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID v4 assigned by the gateway.  Use this in GetTransactionStatus.
	TxnId string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	// Always PENDING immediately after submission.
	// Fraud decision is asynchronous; poll GetTransactionStatus for the result.
	Status TransactionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=sentinel.gateway.v1.TransactionStatus" json:"status,omitempty"`
	// Server-assigned ISO 8601 timestamp (UTC) of when the event was
	// published to Kafka.  Useful for client-side latency tracking.
	SubmittedAt   string `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"` // e.g. "2025-08-15T09:31:00.123Z"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionAck) Reset() {
	*x = TransactionAck{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionAck) ProtoMessage() {}

func (x *TransactionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionAck.ProtoReflect.Descriptor instead.
func (*TransactionAck) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionAck) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TransactionAck) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionAck) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"` // UUID v4 returned by SubmitTransaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type TransactionStatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TxnId  string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Status TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=sentinel.gateway.v1.TransactionStatus" json:"status,omitempty"`
	// Populated only when status is APPROVED or DECLINED.
	// Empty string when status is PENDING or ERROR.
	FraudDecision string `protobuf:"bytes,3,opt,name=fraud_decision,json=fraudDecision,proto3" json:"fraud_decision,omitempty"` // "APPROVE" | "DECLINE" | "REVIEW"
	RiskScore     int32  `protobuf:"varint,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`            // 100–1000; 0 when status is PENDING
	// ISO 8601 UTC timestamps
	SubmittedAt   string `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	DecidedAt     string `protobuf:"bytes,6,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"` // Empty when status is PENDING
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatusResponse) Reset() {
	*x = TransactionStatusResponse{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusResponse) ProtoMessage() {}

func (x *TransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*TransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionStatusResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TransactionStatusResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransactionStatusResponse) GetFraudDecision() string {
	if x != nil {
		return x.FraudDecision
	}
	return ""
}

func (x *TransactionStatusResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *TransactionStatusResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *TransactionStatusResponse) GetDecidedAt() string {
	if x != nil {
		return x.DecidedAt
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\x13sentinel.gateway.v1\"\xb4\x03\n" +
	"\x12TransactionRequest\x12\x1b\n" +
	"\tpan_last4\x18\x01 \x01(\tR\bpanLast4\x12\x1f\n" +
	"\vcard_expiry\x18\x02 \x01(\tR\n" +
	"cardExpiry\x12\x1b\n" +
	"\tcard_hash\x18\x03 \x01(\tR\bcardHash\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\tR\n" +
	"merchantId\x12\x10\n" +
	"\x03mcc\x18\a \x01(\tR\x03mcc\x12O\n" +
	"\x10transaction_type\x18\b \x01(\x0e2$.sentinel.gateway.v1.TransactionTypeR\x0ftransactionType\x126\n" +
	"\achannel\x18\t \x01(\x0e2\x1c.sentinel.gateway.v1.ChannelR\achannel\x12\x1f\n" +
	"\vterminal_id\x18\v \x01(\tR\n" +
	"terminalId\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\"\x8a\x01\n" +
	"\x0eTransactionAck\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.sentinel.gateway.v1.TransactionStatusR\x06status\x12!\n" +
	"\fsubmitted_at\x18\x03 \x01(\tR\vsubmittedAt\"&\n" +
	"\rStatusRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"\xfa\x01\n" +
	"\x19TransactionStatusResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.sentinel.gateway.v1.TransactionStatusR\x06status\x12%\n" +
	"\x0efraud_decision\x18\x03 \x01(\tR\rfraudDecision\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x05R\triskScore\x12!\n" +
	"\fsubmitted_at\x18\x05 \x01(\tR\vsubmittedAt\x12\x1d\n" +
	"\n" +
	"decided_at\x18\x06 \x01(\tR\tdecidedAt*w\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bDECLINED\x10\x03\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x05*b\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05SALES\x10\x01\x12\b\n" +
	"\x04VOID\x10\x02\x12\n" +
	"\n" +
	"\x06REFUND\x10\x03\x12\f\n" +
	"\bREVERSAL\x10\x04*3\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03POS\x10\x01\x12\x06\n" +
	"\x02PG\x10\x022\xdf\x01\n" +
	"\x0eGatewayService\x12a\n" +
	"\x11SubmitTransaction\x12'.sentinel.gateway.v1.TransactionRequest\x1a#.sentinel.gateway.v1.TransactionAck\x12j\n" +
	"\x14GetTransactionStatus\x12\".sentinel.gateway.v1.StatusRequest\x1a..sentinel.gateway.v1.TransactionStatusResponseB[\n" +
	"\x1dcom.sentinelswitch.gateway.v1B\fGatewayProtoP\x01Z*github.com/sentinelswitch/proto/gateway/v1b\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gateway_proto_goTypes = []any{
	(TransactionStatus)(0),            // 0: sentinel.gateway.v1.TransactionStatus
	(TransactionType)(0),              // 1: sentinel.gateway.v1.TransactionType
	(Channel)(0),                      // 2: sentinel.gateway.v1.Channel
	(*TransactionRequest)(nil),        // 3: sentinel.gateway.v1.TransactionRequest
	(*TransactionAck)(nil),            // 4: sentinel.gateway.v1.TransactionAck
	(*StatusRequest)(nil),             // 5: sentinel.gateway.v1.StatusRequest
	(*TransactionStatusResponse)(nil), // 6: sentinel.gateway.v1.TransactionStatusResponse
}
var file_proto_gateway_proto_depIdxs = []int32{
	1, // 0: sentinel.gateway.v1.TransactionRequest.transaction_type:type_name -> sentinel.gateway.v1.TransactionType
	2, // 1: sentinel.gateway.v1.TransactionRequest.channel:type_name -> sentinel.gateway.v1.Channel
	0, // 2: sentinel.gateway.v1.TransactionAck.status:type_name -> sentinel.gateway.v1.TransactionStatus
	0, // 3: sentinel.gateway.v1.TransactionStatusResponse.status:type_name -> sentinel.gateway.v1.TransactionStatus
	3, // 4: sentinel.gateway.v1.GatewayService.SubmitTransaction:input_type -> sentinel.gateway.v1.TransactionRequest
	5, // 5: sentinel.gateway.v1.GatewayService.GetTransactionStatus:input_type -> sentinel.gateway.v1.StatusRequest
	4, // 6: sentinel.gateway.v1.GatewayService.SubmitTransaction:output_type -> sentinel.gateway.v1.TransactionAck
	6, // 7: sentinel.gateway.v1.GatewayService.GetTransactionStatus:output_type -> sentinel.gateway.v1.TransactionStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		EnumInfos:         file_proto_gateway_proto_enumTypes,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
