// =============================================================================
// SentinelSwitch — Kafka Topic Schema
// Topic  : transactions
// Ticket : CREDO-ALERT-001
// Registry subject : transactions-value
// Compatibility    : BACKWARD
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/transactions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_SALES                        TransactionType = 1
	TransactionType_VOID                         TransactionType = 2
	TransactionType_REFUND                       TransactionType = 3
	TransactionType_REVERSAL                     TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "SALES",
		2: "VOID",
		3: "REFUND",
		4: "REVERSAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"SALES":                        1,
		"VOID":                         2,
		"REFUND":                       3,
		"REVERSAL":                     4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_POS                 Channel = 1
	Channel_PG                  Channel = 2 // Payment Gateway
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "POS",
		2: "PG",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"POS":                 1,
		"PG":                  2,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[1].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[1]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{1}
}

type Scheme int32

const (
	Scheme_SCHEME_UNSPECIFIED Scheme = 0
	Scheme_MASTERCARD         Scheme = 1
	Scheme_VISA               Scheme = 2
	Scheme_AMEX               Scheme = 3
	Scheme_UNION_PAY          Scheme = 4
)

// Enum value maps for Scheme.
var (
	Scheme_name = map[int32]string{
		0: "SCHEME_UNSPECIFIED",
		1: "MASTERCARD",
		2: "VISA",
		3: "AMEX",
		4: "UNION_PAY",
	}
	Scheme_value = map[string]int32{
		"SCHEME_UNSPECIFIED": 0,
		"MASTERCARD":         1,
		"VISA":               2,
		"AMEX":               3,
		"UNION_PAY":          4,
	}
)

func (x Scheme) Enum() *Scheme {
	p := new(Scheme)
	*p = x
	return p
}

func (x Scheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scheme) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[2].Descriptor()
}

func (Scheme) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[2]
}

func (x Scheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scheme.Descriptor instead.
func (Scheme) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{2}
}

type TransactionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ------------------------------------------------------------------
	// Identity
	// ------------------------------------------------------------------
	TxnId        string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`                      // UUID v4 — generated by API Gateway
	TxnTimestamp string `protobuf:"bytes,2,opt,name=txn_timestamp,json=txnTimestamp,proto3" json:"txn_timestamp,omitempty"` // ISO 8601 e.g. "2025-01-15T14:30:00Z"
	// ------------------------------------------------------------------
	// Card (PCI-DSS safe — no raw PAN)
	// ------------------------------------------------------------------
	CardHash  string `protobuf:"bytes,3,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`    // SHA256(PAN + system_salt), hex 64 chars
	MaskedPan string `protobuf:"bytes,4,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"` // e.g. "411111XXXXXX1111" — display only
	// ------------------------------------------------------------------
	// Amount (minor currency units to avoid floating-point errors)
	// e.g. OMR 5.250 → amount_minor = 5250, currency = "OMR" (3 decimals)
	//
	//	INR 5000  → amount_minor = 500000, currency = "INR" (2 decimals)
	//
	// ------------------------------------------------------------------
	AmountMinor int64  `protobuf:"varint,5,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency    string `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217 e.g. "OMR", "INR", "USD"
	// ------------------------------------------------------------------
	// Merchant & Terminal
	// ------------------------------------------------------------------
	MerchantId string `protobuf:"bytes,7,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TerminalId string `protobuf:"bytes,8,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Mcc        string `protobuf:"bytes,9,opt,name=mcc,proto3" json:"mcc,omitempty"` // ISO 18245 4-digit code e.g. "5411"
	// ------------------------------------------------------------------
	// Transaction Classification
	// ------------------------------------------------------------------
	TransactionType TransactionType `protobuf:"varint,10,opt,name=transaction_type,json=transactionType,proto3,enum=sentinel.transactions.v1.TransactionType" json:"transaction_type,omitempty"`
	Channel         Channel         `protobuf:"varint,11,opt,name=channel,proto3,enum=sentinel.transactions.v1.Channel" json:"channel,omitempty"`
	Scheme          Scheme          `protobuf:"varint,12,opt,name=scheme,proto3,enum=sentinel.transactions.v1.Scheme" json:"scheme,omitempty"`
	// ------------------------------------------------------------------
	// Network Reference
	// ------------------------------------------------------------------
	Rrn           string `protobuf:"bytes,13,opt,name=rrn,proto3" json:"rrn,omitempty"` // Retrieval Reference Number — 12 chars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_proto_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEvent) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *TransactionEvent) GetTxnTimestamp() string {
	if x != nil {
		return x.TxnTimestamp
	}
	return ""
}

func (x *TransactionEvent) GetCardHash() string {
	if x != nil {
		return x.CardHash
	}
	return ""
}

func (x *TransactionEvent) GetMaskedPan() string {
	if x != nil {
		return x.MaskedPan
	}
	return ""
}

func (x *TransactionEvent) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *TransactionEvent) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionEvent) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *TransactionEvent) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TransactionEvent) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *TransactionEvent) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionEvent) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *TransactionEvent) GetScheme() Scheme {
	if x != nil {
		return x.Scheme
	}
	return Scheme_SCHEME_UNSPECIFIED
}

func (x *TransactionEvent) GetRrn() string {
	if x != nil {
		return x.Rrn
	}
	return ""
}

var File_proto_transactions_proto protoreflect.FileDescriptor

const file_proto_transactions_proto_rawDesc = "" +
	"\n" +
	"\x18proto/transactions.proto\x12\x18sentinel.transactions.v1\"\xfc\x03\n" +
	"\x10TransactionEvent\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12#\n" +
	"\rtxn_timestamp\x18\x02 \x01(\tR\ftxnTimestamp\x12\x1b\n" +
	"\tcard_hash\x18\x03 \x01(\tR\bcardHash\x12\x1d\n" +
	"\n" +
	"masked_pan\x18\x04 \x01(\tR\tmaskedPan\x12!\n" +
	"\famount_minor\x18\x05 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmerchant_id\x18\a \x01(\tR\n" +
	"merchantId\x12\x1f\n" +
	"\vterminal_id\x18\b \x01(\tR\n" +
	"terminalId\x12\x10\n" +
	"\x03mcc\x18\t \x01(\tR\x03mcc\x12T\n" +
	"\x10transaction_type\x18\n" +
	" \x01(\x0e2).sentinel.transactions.v1.TransactionTypeR\x0ftransactionType\x12;\n" +
	"\achannel\x18\v \x01(\x0e2!.sentinel.transactions.v1.ChannelR\achannel\x128\n" +
	"\x06scheme\x18\f \x01(\x0e2 .sentinel.transactions.v1.SchemeR\x06scheme\x12\x10\n" +
	"\x03rrn\x18\r \x01(\tR\x03rrn*b\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05SALES\x10\x01\x12\b\n" +
	"\x04VOID\x10\x02\x12\n" +
	"\n" +
	"\x06REFUND\x10\x03\x12\f\n" +
	"\bREVERSAL\x10\x04*3\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03POS\x10\x01\x12\x06\n" +
	"\x02PG\x10\x02*S\n" +
	"\x06Scheme\x12\x16\n" +
	"\x12SCHEME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"MASTERCARD\x10\x01\x12\b\n" +
	"\x04VISA\x10\x02\x12\b\n" +
	"\x04AMEX\x10\x03\x12\r\n" +
	"\tUNION_PAY\x10\x04Bi\n" +
	"\"com.sentinelswitch.transactions.v1B\x10TransactionProtoP\x01Z/github.com/sentinelswitch/proto/transactions/v1b\x06proto3"

var (
	file_proto_transactions_proto_rawDescOnce sync.Once
	file_proto_transactions_proto_rawDescData []byte
)

func file_proto_transactions_proto_rawDescGZIP() []byte {
	file_proto_transactions_proto_rawDescOnce.Do(func() {
		file_proto_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)))
	})
	return file_proto_transactions_proto_rawDescData
}

var file_proto_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_transactions_proto_goTypes = []any{
	(TransactionType)(0),     // 0: sentinel.transactions.v1.TransactionType
	(Channel)(0),             // 1: sentinel.transactions.v1.Channel
	(Scheme)(0),              // 2: sentinel.transactions.v1.Scheme
	(*TransactionEvent)(nil), // 3: sentinel.transactions.v1.TransactionEvent
}
var file_proto_transactions_proto_depIdxs = []int32{
	0, // 0: sentinel.transactions.v1.TransactionEvent.transaction_type:type_name -> sentinel.transactions.v1.TransactionType
	1, // 1: sentinel.transactions.v1.TransactionEvent.channel:type_name -> sentinel.transactions.v1.Channel
	2, // 2: sentinel.transactions.v1.TransactionEvent.scheme:type_name -> sentinel.transactions.v1.Scheme
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_transactions_proto_init() }
func file_proto_transactions_proto_init() {
	if File_proto_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_transactions_proto_goTypes,
		DependencyIndexes: file_proto_transactions_proto_depIdxs,
		EnumInfos:         file_proto_transactions_proto_enumTypes,
		MessageInfos:      file_proto_transactions_proto_msgTypes,
	}.Build()
	File_proto_transactions_proto = out.File
	file_proto_transactions_proto_goTypes = nil
	file_proto_transactions_proto_depIdxs = nil
}
