// =============================================================================
// SentinelSwitch — gRPC Service Contract
// Service : RiskService
// Ticket  : CREDO-ALERT-001
// Fix     : amount changed from double → int64 (minor units) to avoid
//           floating-point representation errors on amounts like OMR 5.250
// Ticket  : CREDO-ALERT-002
// Fix     : RiskRequest.features (FraudFeatures) added to carry the full
//           11-field feature vector defined in fraud-rules.yaml.
//           Fields 7–9 (velocity_window / velocity_count / velocity_amount)
//           are superseded and reserved; they modelled only a single velocity
//           window which is insufficient for multi-window risk scoring.
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/risk.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RiskService_CalculateRisk_FullMethodName = "/sentinel.risk.v1.RiskService/CalculateRisk"
)

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskServiceClient interface {
	CalculateRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) CalculateRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, RiskService_CalculateRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations should embed UnimplementedRiskServiceServer
// for forward compatibility.
type RiskServiceServer interface {
	CalculateRisk(context.Context, *RiskRequest) (*RiskResponse, error)
}

// UnimplementedRiskServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServiceServer struct{}

func (UnimplementedRiskServiceServer) CalculateRisk(context.Context, *RiskRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateRisk not implemented")
}
func (UnimplementedRiskServiceServer) testEmbeddedByValue() {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	// If the following call panics, it indicates UnimplementedRiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_CalculateRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CalculateRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CalculateRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CalculateRisk(ctx, req.(*RiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.risk.v1.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRisk",
			Handler:    _RiskService_CalculateRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/risk.proto",
}
