// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: risk/v1/risk.proto

package v1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// RiskServiceClient is the client API for RiskService service.
type RiskServiceClient interface {
	CalculateRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewRiskServiceClient creates a new RiskServiceClient.
func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) CalculateRisk(ctx context.Context, in *RiskRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, "/risk.v1.RiskService/CalculateRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility.
type RiskServiceServer interface {
	CalculateRisk(context.Context, *RiskRequest) (*RiskResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRiskServiceServer struct{}

func (UnimplementedRiskServiceServer) CalculateRisk(context.Context, *RiskRequest) (*RiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRisk not implemented")
}

func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

// RegisterRiskServiceServer registers the RiskServiceServer to the gRPC server.
func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_CalculateRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CalculateRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/risk.v1.RiskService/CalculateRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CalculateRisk(ctx, req.(*RiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.v1.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRisk",
			Handler:    _RiskService_CalculateRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk/v1/risk.proto",
}
