// =============================================================================
// SentinelSwitch — gRPC Service Contract
// Service : RiskService
// Ticket  : CREDO-ALERT-001
// Fix     : amount changed from double → int64 (minor units) to avoid
//           floating-point representation errors on amounts like OMR 5.250
// Ticket  : CREDO-ALERT-002
// Fix     : RiskRequest.features (FraudFeatures) added to carry the full
//           11-field feature vector defined in fraud-rules.yaml.
//           Fields 7–9 (velocity_window / velocity_count / velocity_amount)
//           are superseded and reserved; they modelled only a single velocity
//           window which is insufficient for multi-window risk scoring.
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/risk.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_SALES                        TransactionType = 1
	TransactionType_VOID                         TransactionType = 2
	TransactionType_REFUND                       TransactionType = 3
	TransactionType_REVERSAL                     TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "SALES",
		2: "VOID",
		3: "REFUND",
		4: "REVERSAL",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"SALES":                        1,
		"VOID":                         2,
		"REFUND":                       3,
		"REVERSAL":                     4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_risk_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_risk_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{0}
}

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_POS                 Channel = 1
	Channel_PG                  Channel = 2
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "POS",
		2: "PG",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"POS":                 1,
		"PG":                  2,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_risk_proto_enumTypes[1].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_proto_risk_proto_enumTypes[1]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{1}
}

// ------------------------------------------------------------------
// VelocityWindow — retained for internal tooling / monitoring use.
// No longer forwarded in RiskRequest (superseded by FraudFeatures).
//
// Window constants (milliseconds):
//
//	WINDOW_1MIN =     60 000
//	WINDOW_5MIN =    300 000
//	WINDOW_1H   =  3 600 000
//
// ------------------------------------------------------------------
type VelocityWindow int32

const (
	VelocityWindow_VELOCITY_WINDOW_UNSPECIFIED VelocityWindow = 0
	VelocityWindow_WINDOW_1MIN                 VelocityWindow = 1 // 60 seconds  — spike detection
	VelocityWindow_WINDOW_5MIN                 VelocityWindow = 2 // 5 minutes   — short burst detection
	VelocityWindow_WINDOW_1H                   VelocityWindow = 3 // 1 hour      — standard velocity
)

// Enum value maps for VelocityWindow.
var (
	VelocityWindow_name = map[int32]string{
		0: "VELOCITY_WINDOW_UNSPECIFIED",
		1: "WINDOW_1MIN",
		2: "WINDOW_5MIN",
		3: "WINDOW_1H",
	}
	VelocityWindow_value = map[string]int32{
		"VELOCITY_WINDOW_UNSPECIFIED": 0,
		"WINDOW_1MIN":                 1,
		"WINDOW_5MIN":                 2,
		"WINDOW_1H":                   3,
	}
)

func (x VelocityWindow) Enum() *VelocityWindow {
	p := new(VelocityWindow)
	*p = x
	return p
}

func (x VelocityWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VelocityWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_risk_proto_enumTypes[2].Descriptor()
}

func (VelocityWindow) Type() protoreflect.EnumType {
	return &file_proto_risk_proto_enumTypes[2]
}

func (x VelocityWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VelocityWindow.Descriptor instead.
func (VelocityWindow) EnumDescriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{2}
}

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVE              Decision = 1
	Decision_DECLINE              Decision = 2
	Decision_REVIEW               Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "APPROVE",
		2: "DECLINE",
		3: "REVIEW",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"APPROVE":              1,
		"DECLINE":              2,
		"REVIEW":               3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_risk_proto_enumTypes[3].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_proto_risk_proto_enumTypes[3]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{3}
}

type RiskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ------------------------------------------------------------------
	// Transaction identity
	// ------------------------------------------------------------------
	TxnId string `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"` // UUID v4 — for correlation in logs
	// ------------------------------------------------------------------
	// Card (hashed — no raw PAN crosses service boundary)
	// ------------------------------------------------------------------
	CardHash string `protobuf:"bytes,2,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`
	// ------------------------------------------------------------------
	// Amount (minor currency units — avoids float rounding)
	// e.g. OMR 5.250 → amount_minor = 5250, currency = "OMR"
	// ------------------------------------------------------------------
	AmountMinor int64  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency    string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217
	// ------------------------------------------------------------------
	// Merchant context
	// ------------------------------------------------------------------
	MerchantId string `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Mcc        string `protobuf:"bytes,6,opt,name=mcc,proto3" json:"mcc,omitempty"` // ISO 18245
	// ------------------------------------------------------------------
	// Classification (context for rule evaluation)
	// ------------------------------------------------------------------
	TransactionType TransactionType `protobuf:"varint,10,opt,name=transaction_type,json=transactionType,proto3,enum=sentinel.risk.v1.TransactionType" json:"transaction_type,omitempty"`
	Channel         Channel         `protobuf:"varint,11,opt,name=channel,proto3,enum=sentinel.risk.v1.Channel" json:"channel,omitempty"`
	// ------------------------------------------------------------------
	// Full feature vector — assembled by Fraud Engine after Step 3.1–3.3
	//
	// Sources (see fraud-rules.yaml § feature_vector):
	//   - Velocity counters  : Redis sorted sets / HyperLogLog
	//   - Merchant risk score: Redis string  merchant_risk:{merchant_id}
	//   - Rule flags         : output of Step 3.1 rule evaluation
	//
	// All counts exclude the current transaction (prior txns only).
	// All amounts are in minor currency units (same unit as amount_minor).
	// ------------------------------------------------------------------
	Features      *FraudFeatures `protobuf:"bytes,12,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
	mi := &file_proto_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRequest.ProtoReflect.Descriptor instead.
func (*RiskRequest) Descriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *RiskRequest) GetCardHash() string {
	if x != nil {
		return x.CardHash
	}
	return ""
}

func (x *RiskRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *RiskRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RiskRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RiskRequest) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *RiskRequest) GetTransactionType() TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *RiskRequest) GetChannel() Channel {
	if x != nil {
		return x.Channel
	}
	return Channel_CHANNEL_UNSPECIFIED
}

func (x *RiskRequest) GetFeatures() *FraudFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

// ------------------------------------------------------------------
// FraudFeatures — full feature vector forwarded to Risk Service.
//
// Assembled by Fraud Engine after Steps 3.1 (rules) + 3.2 (velocity).
// All velocity fields are populated via Redis queries BEFORE the gRPC
// call; the Risk Service must not re-query Redis.
//
// Velocity Redis sources (card:{card_hash}:txns sorted set, score=epoch-ms):
//
//	txn_count_*   → ZCOUNT  key (now_ms - window_ms) now_ms
//	amount_sum_*  → companion HASH (see fraud-rules.yaml § velocity)
//	unique_merchants_5min → HyperLogLog  hll:merchants:{card_hash}:{bucket}
//	unique_terminals_5min → HyperLogLog  hll:terminals:{card_hash}:{bucket}
//	                        (±0.81 % std-err accepted for both — Gap 6 resolved)
//
// ------------------------------------------------------------------
type FraudFeatures struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- Velocity counts (prior transactions only, current excluded) ----
	TxnCount_1Min int32 `protobuf:"varint,1,opt,name=txn_count_1min,json=txnCount1min,proto3" json:"txn_count_1min,omitempty"` // transactions in last 60 s
	TxnCount_5Min int32 `protobuf:"varint,2,opt,name=txn_count_5min,json=txnCount5min,proto3" json:"txn_count_5min,omitempty"` // transactions in last 5 min
	TxnCount_1Hr  int32 `protobuf:"varint,3,opt,name=txn_count_1hr,json=txnCount1hr,proto3" json:"txn_count_1hr,omitempty"`    // transactions in last 60 min
	// ---- Velocity amounts (minor currency units) ----
	AmountSum_1Min int64 `protobuf:"varint,4,opt,name=amount_sum_1min,json=amountSum1min,proto3" json:"amount_sum_1min,omitempty"` // spend in last 60 s
	AmountSum_1Hr  int64 `protobuf:"varint,5,opt,name=amount_sum_1hr,json=amountSum1hr,proto3" json:"amount_sum_1hr,omitempty"`    // spend in last 60 min
	// ---- Cardinality (HyperLogLog — approximate, ±0.81% std-err accepted) ----
	UniqueMerchants_5Min int32 `protobuf:"varint,6,opt,name=unique_merchants_5min,json=uniqueMerchants5min,proto3" json:"unique_merchants_5min,omitempty"`  // distinct merchants in last 5 min
	UniqueTerminals_5Min int32 `protobuf:"varint,11,opt,name=unique_terminals_5min,json=uniqueTerminals5min,proto3" json:"unique_terminals_5min,omitempty"` // distinct terminals in last 5 min
	// ---- Merchant risk (pre-computed score, loaded from DB → Redis) ----
	// Source : merchant_risk:{merchant_id}   TTL: 86400 s
	// Default: 0.5 if key absent (unknown / unclassified merchant)
	// Range  : 0.0 (trusted) → 1.0 (highest risk)
	MerchantRisk float64 `protobuf:"fixed64,7,opt,name=merchant_risk,json=merchantRisk,proto3" json:"merchant_risk,omitempty"`
	// ---- Binary rule flags (0 = not triggered, 1 = triggered) ----
	IsNight          int32 `protobuf:"varint,8,opt,name=is_night,json=isNight,proto3" json:"is_night,omitempty"`                                 // 1 if NIGHT_TRANSACTION rule fired
	IsRiskyMcc       int32 `protobuf:"varint,9,opt,name=is_risky_mcc,json=isRiskyMcc,proto3" json:"is_risky_mcc,omitempty"`                      // 1 if RISKY_MCC rule fired
	IsCardNotPresent int32 `protobuf:"varint,10,opt,name=is_card_not_present,json=isCardNotPresent,proto3" json:"is_card_not_present,omitempty"` // 1 if channel == PG (card-not-present)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FraudFeatures) Reset() {
	*x = FraudFeatures{}
	mi := &file_proto_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudFeatures) ProtoMessage() {}

func (x *FraudFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudFeatures.ProtoReflect.Descriptor instead.
func (*FraudFeatures) Descriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{1}
}

func (x *FraudFeatures) GetTxnCount_1Min() int32 {
	if x != nil {
		return x.TxnCount_1Min
	}
	return 0
}

func (x *FraudFeatures) GetTxnCount_5Min() int32 {
	if x != nil {
		return x.TxnCount_5Min
	}
	return 0
}

func (x *FraudFeatures) GetTxnCount_1Hr() int32 {
	if x != nil {
		return x.TxnCount_1Hr
	}
	return 0
}

func (x *FraudFeatures) GetAmountSum_1Min() int64 {
	if x != nil {
		return x.AmountSum_1Min
	}
	return 0
}

func (x *FraudFeatures) GetAmountSum_1Hr() int64 {
	if x != nil {
		return x.AmountSum_1Hr
	}
	return 0
}

func (x *FraudFeatures) GetUniqueMerchants_5Min() int32 {
	if x != nil {
		return x.UniqueMerchants_5Min
	}
	return 0
}

func (x *FraudFeatures) GetUniqueTerminals_5Min() int32 {
	if x != nil {
		return x.UniqueTerminals_5Min
	}
	return 0
}

func (x *FraudFeatures) GetMerchantRisk() float64 {
	if x != nil {
		return x.MerchantRisk
	}
	return 0
}

func (x *FraudFeatures) GetIsNight() int32 {
	if x != nil {
		return x.IsNight
	}
	return 0
}

func (x *FraudFeatures) GetIsRiskyMcc() int32 {
	if x != nil {
		return x.IsRiskyMcc
	}
	return 0
}

func (x *FraudFeatures) GetIsCardNotPresent() int32 {
	if x != nil {
		return x.IsCardNotPresent
	}
	return 0
}

type RiskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ------------------------------------------------------------------
	// Score: 100 (lowest risk) → 1000 (highest risk)
	// Bands: 100–399 APPROVE | 400–700 REVIEW | 701–1000 DECLINE
	//
	//	(aligns with fraud-rules.yaml: approve_below=400, decline_above=700
	//	 i.e. score > 700 → DECLINE; score = 700 → REVIEW)
	//
	// ------------------------------------------------------------------
	RiskScore int32 `protobuf:"varint,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	// ------------------------------------------------------------------
	// Decision derived from score band
	// ------------------------------------------------------------------
	Decision Decision `protobuf:"varint,2,opt,name=decision,proto3,enum=sentinel.risk.v1.Decision" json:"decision,omitempty"`
	// ------------------------------------------------------------------
	// Rules that contributed to this score
	// ------------------------------------------------------------------
	TriggeredRules []string `protobuf:"bytes,3,rep,name=triggered_rules,json=triggeredRules,proto3" json:"triggered_rules,omitempty"` // e.g. ["HIGH_AMOUNT", "VELOCITY_SPIKE"]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_proto_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_risk_proto_rawDescGZIP(), []int{2}
}

func (x *RiskResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *RiskResponse) GetTriggeredRules() []string {
	if x != nil {
		return x.TriggeredRules
	}
	return nil
}

var File_proto_risk_proto protoreflect.FileDescriptor

const file_proto_risk_proto_rawDesc = "" +
	"\n" +
	"\x10proto/risk.proto\x12\x10sentinel.risk.v1\"\xb7\x03\n" +
	"\vRiskRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x1b\n" +
	"\tcard_hash\x18\x02 \x01(\tR\bcardHash\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12\x10\n" +
	"\x03mcc\x18\x06 \x01(\tR\x03mcc\x12L\n" +
	"\x10transaction_type\x18\n" +
	" \x01(\x0e2!.sentinel.risk.v1.TransactionTypeR\x0ftransactionType\x123\n" +
	"\achannel\x18\v \x01(\x0e2\x19.sentinel.risk.v1.ChannelR\achannel\x12;\n" +
	"\bfeatures\x18\f \x01(\v2\x1f.sentinel.risk.v1.FraudFeaturesR\bfeaturesJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x0fvelocity_windowR\x0evelocity_countR\x0fvelocity_amount\"\xc6\x03\n" +
	"\rFraudFeatures\x12$\n" +
	"\x0etxn_count_1min\x18\x01 \x01(\x05R\ftxnCount1min\x12$\n" +
	"\x0etxn_count_5min\x18\x02 \x01(\x05R\ftxnCount5min\x12\"\n" +
	"\rtxn_count_1hr\x18\x03 \x01(\x05R\vtxnCount1hr\x12&\n" +
	"\x0famount_sum_1min\x18\x04 \x01(\x03R\ramountSum1min\x12$\n" +
	"\x0eamount_sum_1hr\x18\x05 \x01(\x03R\famountSum1hr\x122\n" +
	"\x15unique_merchants_5min\x18\x06 \x01(\x05R\x13uniqueMerchants5min\x122\n" +
	"\x15unique_terminals_5min\x18\v \x01(\x05R\x13uniqueTerminals5min\x12#\n" +
	"\rmerchant_risk\x18\a \x01(\x01R\fmerchantRisk\x12\x19\n" +
	"\bis_night\x18\b \x01(\x05R\aisNight\x12 \n" +
	"\fis_risky_mcc\x18\t \x01(\x05R\n" +
	"isRiskyMcc\x12-\n" +
	"\x13is_card_not_present\x18\n" +
	" \x01(\x05R\x10isCardNotPresent\"\x8e\x01\n" +
	"\fRiskResponse\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x01 \x01(\x05R\triskScore\x126\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1a.sentinel.risk.v1.DecisionR\bdecision\x12'\n" +
	"\x0ftriggered_rules\x18\x03 \x03(\tR\x0etriggeredRules*b\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05SALES\x10\x01\x12\b\n" +
	"\x04VOID\x10\x02\x12\n" +
	"\n" +
	"\x06REFUND\x10\x03\x12\f\n" +
	"\bREVERSAL\x10\x04*3\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03POS\x10\x01\x12\x06\n" +
	"\x02PG\x10\x02*b\n" +
	"\x0eVelocityWindow\x12\x1f\n" +
	"\x1bVELOCITY_WINDOW_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vWINDOW_1MIN\x10\x01\x12\x0f\n" +
	"\vWINDOW_5MIN\x10\x02\x12\r\n" +
	"\tWINDOW_1H\x10\x03*J\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPROVE\x10\x01\x12\v\n" +
	"\aDECLINE\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x032]\n" +
	"\vRiskService\x12N\n" +
	"\rCalculateRisk\x12\x1d.sentinel.risk.v1.RiskRequest\x1a\x1e.sentinel.risk.v1.RiskResponseBR\n" +
	"\x1acom.sentinelswitch.risk.v1B\tRiskProtoP\x01Z'github.com/sentinelswitch/proto/risk/v1b\x06proto3"

var (
	file_proto_risk_proto_rawDescOnce sync.Once
	file_proto_risk_proto_rawDescData []byte
)

func file_proto_risk_proto_rawDescGZIP() []byte {
	file_proto_risk_proto_rawDescOnce.Do(func() {
		file_proto_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_risk_proto_rawDesc), len(file_proto_risk_proto_rawDesc)))
	})
	return file_proto_risk_proto_rawDescData
}

var file_proto_risk_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_risk_proto_goTypes = []any{
	(TransactionType)(0),  // 0: sentinel.risk.v1.TransactionType
	(Channel)(0),          // 1: sentinel.risk.v1.Channel
	(VelocityWindow)(0),   // 2: sentinel.risk.v1.VelocityWindow
	(Decision)(0),         // 3: sentinel.risk.v1.Decision
	(*RiskRequest)(nil),   // 4: sentinel.risk.v1.RiskRequest
	(*FraudFeatures)(nil), // 5: sentinel.risk.v1.FraudFeatures
	(*RiskResponse)(nil),  // 6: sentinel.risk.v1.RiskResponse
}
var file_proto_risk_proto_depIdxs = []int32{
	0, // 0: sentinel.risk.v1.RiskRequest.transaction_type:type_name -> sentinel.risk.v1.TransactionType
	1, // 1: sentinel.risk.v1.RiskRequest.channel:type_name -> sentinel.risk.v1.Channel
	5, // 2: sentinel.risk.v1.RiskRequest.features:type_name -> sentinel.risk.v1.FraudFeatures
	3, // 3: sentinel.risk.v1.RiskResponse.decision:type_name -> sentinel.risk.v1.Decision
	4, // 4: sentinel.risk.v1.RiskService.CalculateRisk:input_type -> sentinel.risk.v1.RiskRequest
	6, // 5: sentinel.risk.v1.RiskService.CalculateRisk:output_type -> sentinel.risk.v1.RiskResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_risk_proto_init() }
func file_proto_risk_proto_init() {
	if File_proto_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_risk_proto_rawDesc), len(file_proto_risk_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_risk_proto_goTypes,
		DependencyIndexes: file_proto_risk_proto_depIdxs,
		EnumInfos:         file_proto_risk_proto_enumTypes,
		MessageInfos:      file_proto_risk_proto_msgTypes,
	}.Build()
	File_proto_risk_proto = out.File
	file_proto_risk_proto_goTypes = nil
	file_proto_risk_proto_depIdxs = nil
}
