// Code generated by protoc-gen-go. DO NOT EDIT.
// source: risk/v1/risk.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// Decision represents the fraud decision outcome.
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVE              Decision = 1
	Decision_DECLINE              Decision = 2
	Decision_REVIEW               Decision = 3
)

var Decision_name = map[int32]string{
	0: "DECISION_UNSPECIFIED",
	1: "APPROVE",
	2: "DECLINE",
	3: "REVIEW",
}

var Decision_value = map[string]int32{
	"DECISION_UNSPECIFIED": 0,
	"APPROVE":              1,
	"DECLINE":              2,
	"REVIEW":               3,
}

func (d Decision) Enum() *Decision {
	p := new(Decision)
	*p = d
	return p
}

func (d Decision) String() string {
	if s, ok := Decision_name[int32(d)]; ok {
		return s
	}
	return "DECISION_UNSPECIFIED"
}

func (d Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(d)
}

// TransactionType classifies the kind of card transaction.
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_SALES                        TransactionType = 1
	TransactionType_VOID                         TransactionType = 2
	TransactionType_REFUND                       TransactionType = 3
	TransactionType_REVERSAL                     TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "TRANSACTION_TYPE_UNSPECIFIED",
	1: "SALES",
	2: "VOID",
	3: "REFUND",
	4: "REVERSAL",
}

var TransactionType_value = map[string]int32{
	"TRANSACTION_TYPE_UNSPECIFIED": 0,
	"SALES":                        1,
	"VOID":                         2,
	"REFUND":                       3,
	"REVERSAL":                     4,
}

func (t TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = t
	return p
}

func (t TransactionType) String() string {
	if s, ok := TransactionType_name[int32(t)]; ok {
		return s
	}
	return "TRANSACTION_TYPE_UNSPECIFIED"
}

func (t TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(t)
}

// Channel represents the payment channel used.
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_POS                 Channel = 1
	Channel_PG                  Channel = 2
)

var Channel_name = map[int32]string{
	0: "CHANNEL_UNSPECIFIED",
	1: "POS",
	2: "PG",
}

var Channel_value = map[string]int32{
	"CHANNEL_UNSPECIFIED": 0,
	"POS":                 1,
	"PG":                  2,
}

func (c Channel) Enum() *Channel {
	p := new(Channel)
	*p = c
	return p
}

func (c Channel) String() string {
	if s, ok := Channel_name[int32(c)]; ok {
		return s
	}
	return "CHANNEL_UNSPECIFIED"
}

func (c Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(c)
}

// FraudFeatures is the feature vector computed from real-time aggregation.
type FraudFeatures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnCount_1Min       int32   `protobuf:"varint,1,opt,name=txn_count_1min,json=txnCount1min,proto3" json:"txn_count_1min,omitempty"`
	TxnCount_5Min       int32   `protobuf:"varint,2,opt,name=txn_count_5min,json=txnCount5min,proto3" json:"txn_count_5min,omitempty"`
	TxnCount_1Hr        int32   `protobuf:"varint,3,opt,name=txn_count_1hr,json=txnCount1hr,proto3" json:"txn_count_1hr,omitempty"`
	AmountSum_1Min      int64   `protobuf:"varint,4,opt,name=amount_sum_1min,json=amountSum1min,proto3" json:"amount_sum_1min,omitempty"`
	AmountSum_1Hr       int64   `protobuf:"varint,5,opt,name=amount_sum_1hr,json=amountSum1hr,proto3" json:"amount_sum_1hr,omitempty"`
	UniqueMerchants_5Min int32  `protobuf:"varint,6,opt,name=unique_merchants_5min,json=uniqueMerchants5min,proto3" json:"unique_merchants_5min,omitempty"`
	UniqueTerminals_5Min int32  `protobuf:"varint,7,opt,name=unique_terminals_5min,json=uniqueTerminals5min,proto3" json:"unique_terminals_5min,omitempty"`
	MerchantRisk        float64 `protobuf:"fixed64,8,opt,name=merchant_risk,json=merchantRisk,proto3" json:"merchant_risk,omitempty"`
	IsNight             int32   `protobuf:"varint,9,opt,name=is_night,json=isNight,proto3" json:"is_night,omitempty"`
	IsRiskyMcc          int32   `protobuf:"varint,10,opt,name=is_risky_mcc,json=isRiskyMcc,proto3" json:"is_risky_mcc,omitempty"`
	IsCardNotPresent    int32   `protobuf:"varint,11,opt,name=is_card_not_present,json=isCardNotPresent,proto3" json:"is_card_not_present,omitempty"`
}

func (x *FraudFeatures) Reset() {
	*x = FraudFeatures{}
}

func (x *FraudFeatures) String() string {
	return ""
}

func (*FraudFeatures) ProtoMessage() {}

func (x *FraudFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

// RiskRequest is sent to the RiskService to score a transaction.
type RiskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId           string          `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	CardHash        string          `protobuf:"bytes,2,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`
	AmountMinor     int64           `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency        string          `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	MerchantId      string          `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Mcc             string          `protobuf:"bytes,6,opt,name=mcc,proto3" json:"mcc,omitempty"`
	TransactionType TransactionType `protobuf:"varint,7,opt,name=transaction_type,json=transactionType,proto3,enum=risk.v1.TransactionType" json:"transaction_type,omitempty"`
	Channel         Channel         `protobuf:"varint,8,opt,name=channel,proto3,enum=risk.v1.Channel" json:"channel,omitempty"`
	Features        *FraudFeatures  `protobuf:"bytes,9,opt,name=features,proto3" json:"features,omitempty"`
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
}

func (x *RiskRequest) String() string {
	return x.TxnId
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

// RiskResponse is returned by the RiskService with score and decision.
type RiskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskScore      int32    `protobuf:"varint,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Decision       Decision `protobuf:"varint,2,opt,name=decision,proto3,enum=risk.v1.Decision" json:"decision,omitempty"`
	TriggeredRules []string `protobuf:"bytes,3,rep,name=triggered_rules,json=triggeredRules,proto3" json:"triggered_rules,omitempty"`
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
}

func (x *RiskResponse) String() string {
	return ""
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

var file_risk_v1_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
