// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction/v1/transaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// TransactionEvent is the Kafka event produced by the API gateway for each
// incoming payment transaction.
type TransactionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId                    string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	IdempotencyKey           string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CardHash                 string                 `protobuf:"bytes,3,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`
	MaskedPan                string                 `protobuf:"bytes,4,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	ExpiryMonth              uint32                 `protobuf:"varint,5,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear               uint32                 `protobuf:"varint,6,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	AmountMinor              int64                  `protobuf:"varint,7,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	CurrencyCode             string                 `protobuf:"bytes,8,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	TransactionType          string                 `protobuf:"bytes,9,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Channel                  string                 `protobuf:"bytes,10,opt,name=channel,proto3" json:"channel,omitempty"`
	MerchantCategoryCode     string                 `protobuf:"bytes,11,opt,name=merchant_category_code,json=merchantCategoryCode,proto3" json:"merchant_category_code,omitempty"`
	TerminalId               string                 `protobuf:"bytes,12,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	MerchantId               string                 `protobuf:"bytes,13,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	RetrievalReferenceNumber string                 `protobuf:"bytes,14,opt,name=retrieval_reference_number,json=retrievalReferenceNumber,proto3" json:"retrieval_reference_number,omitempty"`
	ReceivedAt               *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
}

func (x *TransactionEvent) String() string {
	return x.TxnId
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.Zero()
}

var file_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
